export const bannerLists = [
    {
        id: 1,
        image: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=1400&q=80",
        title: "컴퓨팅 셋업 업그레이드",
        subtitle: "모니터 · 키보드 · 허브",
        description: "키보드와 모니터, 허브처럼 자주 쓰는 데스크 전자제품을 중심으로 작업 공간 구성을 빠르게 정리할 수 있습니다.",
        categoryLabel: "컴퓨팅",
        highlight: "집중형 데스크 구성",
        tags: ["기계식 키보드", "모니터", "USB-C 허브"],
    },
    {
        id: 2,
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1400&q=80",
        title: "오디오 환경 핵심 장비",
        subtitle: "헤드폰 · 스피커",
        description: "음악 감상과 화상 회의에 모두 어울리는 헤드폰과 스피커를 한 번에 비교하고 고를 수 있습니다.",
        categoryLabel: "오디오",
        highlight: "몰입감 있는 사운드",
        tags: ["노이즈 캔슬링", "북셀프 스피커", "프리미엄 헤드폰"],
    },
    {
        id: 3,
        image: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=1400&q=80",
        title: "게이밍과 충전 액세서리",
        subtitle: "게임패드 · 충전 스탠드",
        description: "게임패드와 충전 액세서리처럼 사용 빈도가 높은 주변기기만 따로 모아 빠르게 선택할 수 있습니다.",
        categoryLabel: "게이밍 · 모바일",
        highlight: "플레이와 충전 동시 구성",
        tags: ["무선 게임패드", "맥세이프 충전", "모바일 액세서리"],
    },
];
